version: "3"
services:
  pool:
    image: immushroom/mintme:latest
    ports:
    - 3333:3333
    - 8888:8888
    depends_on:
    - core-geth
    - redis
    volumes:
    - ./conf/pool/config.json:/app/config.json
    - ./conf/pool/environment.js:/app/www/config/environment.js
    - assets:/app/www/dist
  core-geth:
    image: etclabscore/core-geth
    ports:
    - 30303:30303
    - 8545:8545
    command: '--mintme --nodiscover --maxpeers 0 --http --http.addr 0.0.0.0 --http.port 8545 --http.vhosts "*" --verbosity 5'
    volumes:
    - '$HOME/core-geth:/root'
  redis:
    image: redis
    volumes:
    - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: "redis-server /usr/local/etc/redis/redis.conf"
  nginx:
    image: nginx:latest
    ports:
      - 8000:8000
      - 8080:8080
    depends_on:
      - pool
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - assets:/var/www/html/

volumes:
  assets: